// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxobcffimbxymfrknznc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4b2JjZmZpbWJ4eW1mcmtuem5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDk2MDAsImV4cCI6MjA1OTg4NTYwMH0.d6Vg-QkVREY0-k6dmDsjWeKLnflIvYD9CggBZA5oRmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);